### ISSUE TITLE
Incorrect formatting when using SPACe

### ISSUE THREAD

**Issue by Johnne25** [ejmudi/react-autocomplete-hint#11]
Works well for single words, but hint formatting gettings messed up when you encounter a space in your hintdata.

Typing in 'PURPLE' shows 'PURPLE FLOWER' as the hint.
However, when you type the <space> between purple and flower the formatting becomes messaged up.

Can this be fixed ASAP?

**Comment by ejmudi** [comment]
I'm taking a look at this.

**Comment by ejmudi** [comment]
bugfix: https://github.com/ejmudi/react-autocomplete-hint/releases/tag/v1.2.1
