### ISSUE TITLE
Converting text to UPPER case seems to not format the hint correctly.

### ISSUE THREAD

**Issue by Johnne25** [ejmudi/react-autocomplete-hint#13]
I need the Input to be all in uppercase.  There is PROP passed to allow turning the UPPER / LOWERCASE  on and off.  The isActive is used to display the floating label.   I am using this method to accomplish this:

```
  handleTextChange = (event) => {
    const input = event.target;
    const start = input.selectionStart;
    const end = input.selectionEnd;
  
    let newtext = input.value;
 
    console.log(newtext);

    if (this.props.uppercase) {
     this.setState(
       {value: input.value.toUpperCase()},
       () => input.setSelectionRange(start, end)
     );
   } else if (this.props.lowercase) {
     this.setState(
       {value: input.value.toLowerCase()},
       () => input.setSelectionRange(start, end)
     );
    } else {
     this.setState(
       {value: input.value }
     );
    }
   if (newtext !== '') {
       this.setState({
         isActive: true
       });
     } else {
       this.setState({
         isActive: false
       });
     }   
  }
```

The hintData has already been converted to UPPERCASE.  It uses a preset ARRAY, no need to fetch data with AXIO.

NOTE:  If you click outside the Input component and click back in the hint is displayed correctly.
<img width="155" alt="Screen Shot 2021-01-23 at 6 55 33 PM" src="https://user-images.githubusercontent.com/5278934/105617550-bc4f3e00-5dac-11eb-9d84-eb4dd057ec79.png">
<img width="155" alt="Screen Shot 2021-01-23 at 6 55 05 PM" src="https://user-images.githubusercontent.com/5278934/105617552-beb19800-5dac-11eb-8764-195f4b09ea97.png">

**Comment by Johnne25** [comment]
Note:  That if you actually use UPPERCASE character in the input it seems to work correctly. Only the conversion of the lowercase to uppercase does the formatting issue happen.

**Comment by ejmudi** [comment]
@Johnne25 I published a bugfix to handle cases like this here: https://github.com/ejmudi/react-autocomplete-hint/releases/tag/v1.2.2

To use it in this case, you could modify your code to be something like this:
```
  changeCase = (value) => {
    if (this.props.uppercase) {
      return value.toUpperCase();
    } else if (this.props.lowercase) {
      return value.toLowerCase();
    } else {
      return value;
    }
  }

  handleTextChange = (event) => {
    const input = event.target;
    const start = input.selectionStart;
    const end = input.selectionEnd;

    let newtext = input.value;

    this.setState(
      { value: this.changeCase(input.value) },
      () => {
        if(this.props.uppercase || this.props.lowercase){
          input.setSelectionRange(start, end);
        }
      }
    );

    if (newtext !== '') {
      this.setState({
        isActive: true
      });
    } else {
      this.setState({
        isActive: false
      });
    }
  }

  render = () => {
    return (
      <Hint options={options} valueModifier={this.changeCase}>
        <input
          value={this.state.value}
          onChange={this.handleTextChange} />
      </Hint>
    );
  }
```
