### ISSUE TITLE
onHint prop or something similar

### ISSUE THREAD

**Issue by tilnea** [ejmudi/react-autocomplete-hint#18]
Hi, 

I wonder if you would like to att a onHint/onTyping or a prop so that I can set the hint as a state in my code.

**Is your feature request related to a problem? Please describe.**
I want to autocomplete to the hinting text on enter, not o tab. I guess a lot of other people might have other reasons why they would like to know what the current hint is.

**Describe the solution you'd like**
A prop that gives me the hint text so I can save it to my own state.

**Describe alternatives you've considered**
A prop so I can decide what the key to autofill on. But I believe its more useful to know the current hint.

**Comment by tilnea** [comment]
I made a PR

**Comment by ejmudi** [comment]
Feature published: [https://github.com/ejmudi/react-autocomplete-hint/releases/tag/v1.3.0](https://github.com/ejmudi/react-autocomplete-hint/releases/tag/v1.3.0)
