### ISSUE TITLE
Allow styling of the Hint div itself

### ISSUE THREAD

**Issue by MislavPeric** [ejmudi/react-autocomplete-hint#21]
**Describe the solution you'd like**
I'd like an option that allows us to further style the `Hint` component itself, currently, I don't see a way of doing it so it remains at the fixed width which doesn't fit the current styling of my page

**Describe alternatives you've considered**
Tried wrapping it around with a div to style the width

**Comment by ejmudi** [comment]
You could place the Hint component in a container div and specify the width you want on the container div.

The Hint component will have the same width with your container.

**Comment by MislavPeric** [comment]
@ejmudi Not really a solution. As shown in this example
`              <div className={style.test}>
              <Hint options={options} allowTabFill={true}>
                <input
                  value={formik.values.company}
                  onChange={formik.handleChange}
                  className={style.inputGeneral}
                  name="company"
                  type='text'
                  />
              </Hint>
              </div>`
Wrapping the `Hint` in a div with this class
`.test {
  background-color:black;
  width: 200%
}`              
Results in this
![Screenshot_1](https://user-images.githubusercontent.com/23200555/113402873-0bfe4700-93a6-11eb-9008-8ec71f1b170d.png)

**Comment by smartoryu** [comment]
> You could place the Hint component in a container div and specify the width you want on the container div.
> 
> The Hint component will have the same width with your container.

I see you already putting an inline style with 100% width on the input, but the div wrapper with className "rah-hint-wrapper" is not so the width from our own div is not inherited. Should I fix it for you?

**Comment by ejmudi** [comment]
@smartoryu Sure, you can please go ahead and create a PR.

**Comment by dimitrileduc** [comment]
Hello, i have tried to custom style in .input-with-hint css class. 
But how can i change the auto-complete text color ? ( grey -> white ) 
Thanks in advance

**Comment by ejmudi** [comment]
This is mostly likely resolved by https://github.com/ejmudi/react-autocomplete-hint/pull/32
Closing!
