### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

### ISSUE THREAD

**Issue by qkreltms** [ejmudi/react-autocomplete-hint#7]
**Describe the bug**
It occurs when I use `react-strap@8.5.1` which uses class component with Hint.

**To Reproduce**
```ts
<InputGroup>
        <Hint options={labels.map(label => label.group)}>
          <Input
            type="text"
            placeholder="Search"
            onChange={onChangeSearchHandler}
            value={search}
          />
        </Hint>
        <InputGroupAddon addonType="append">
          <InputGroupText>
            <SearchIcon />
          </InputGroupText>
        </InputGroupAddon>
      </InputGroup>
```

**Screenshots**
[localhost-1609206487051.log](https://github.com/ejmudi/react-autocomplete-hint/files/5749328/localhost-1609206487051.log)
![img](https://user-images.githubusercontent.com/25196026/103253318-03bbf780-49c4-11eb-99a9-65948a01bd47.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 1.2.0

**Additional context**
Seems occurs due to class component because `react strap` uses innerRef which is referencing child DOM of class component.
We should support class component about injecting ref as a props of Hint.
```js
<Hint options={...} childRef={childRef}>
  <Child innerRef={childRef} />
</Hint>
```

**Comment by ejmudi** [comment]
This was happening because 'Hint' only accepts an 'input' element not a component as child.
Added a check for 'input' type in #15
