### ISSUE TITLE
Styling Prop

### ISSUE THREAD

**Issue by Qudusayo** [ejmudi/react-autocomplete-hint#8]
## Styling needs to be fixed  
In my application which I have a predefined styling for my project, the **Hint** automatically overrides my styles and shorten  the width of my input, so I dropped it.  
Look into that and give a fix

**Comment by ejmudi** [comment]
Can you show me an example of what your style looks like for the input?

**Comment by Qudusayo** [comment]
Already removed the package, but the main result is that it shortened the length of my input
