### ISSUE TITLE
String Only

### ISSUE THREAD

**Issue by Qudusayo** [ejmudi/react-autocomplete-hint#9]
## error: to lowerCase() of undefined

I have an input with that of numbers, but its been rejected and throwing error.  
You ought to accept numbers too and can then convert it to string behind the scenes so far all input will be strings

**Comment by ejmudi** [comment]
This library is meant to handle text suggestion and completion. I don't see suggestion/completion of numbers as a frequently recurring use case or one that we would be willing to implement in this library.

The best way I think for you to handle this is to use an input of type `text` so your numbers will be auto converted to strings in the input and you can then decide to converted back to number after the autocomplete.

I'll go ahead with closing this.
